name: platform_maps_flutter
description: A Flutter package that combines google_maps and apple_maps to provide a crossplatform native map implementation.
version: 1.0.2
homepage: https://github.com/ByteList/
repository: https://github.com/ByteList/platform_maps_flutter
issue_tracker: https://github.com/ByteList/platform_maps_flutter/issues
publish_to: none

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_maps_flutter: ^2.10.0
  google_maps_flutter_platform_interface: ^2.9.5
  apple_maps_flutter:
    git:
      url: https://github.com/muxable/apple_maps_flutter.git
      ref: color-scheme

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.1
